<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function searchMovies($name)
    {

        $qb = $this->createQueryBuilder('o');

        $qb->select('o')
            ->leftJoin('o.class','class')
            ->where('class.account = :account')
            ->setParameter('account',$account)
        ;
        return $qb->getQuery()->getResult();
    }
}
