<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function searchMovies($name,$year)
    {
        $name = '%'.$name.'%';

        $qb = $this->createQueryBuilder('o');

        $qb->select('o')
            ->orWhere('o.name LIKE :name')
            ->orWhere('o.year LIKE :year')
            ->setParameter('name',$name)
            ->setParameter('year',$year)
        ;
        return $qb->getQuery()->getResult();
    }
}
